apiVersion: apps/v1
kind: Deployment
metadata:
 name: abc-application
spec:
 replicas: 2
 selector:
   matchLabels:
     name: abc-application
 template:
   metadata:
     labels:
       name: abc-application
   spec:
     containers:
       - image: chandu9999/abc-technologies
         name: app
         ports:
         - name: tcpport
           containerPort: 8080
          
---
apiVersion: v1
kind: Service
metadata:
 name: abc-application
spec:
 type: NodePort
 selector:
   name: abc-application
 ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30080
